import { renderApollo, screen } from '../utils/test-utils';
import CountryList, { COUNTRIES } from './CountryList';
import { cache } from '../cache';

test('renders learn react link', () => {
  const mocks = [
    {
      request: { query: COUNTRIES, variables: { launchId: 1 } },
      result: {
        data: {
          countries: [
            { name: 'Andorra', code: 'AD', emoji: '🇦🇩', phone: '376', __typename: 'Country' },
            {
              name: 'United Arab Emirates',
              code: 'AE',
              emoji: '🇦🇪',
              phone: '971',
              __typename: 'Country',
            },
            { name: 'Afghanistan', code: 'AF', emoji: '🇦🇫', phone: '93', __typename: 'Country' },
            {
              name: 'Antigua and Barbuda',
              code: 'AG',
              emoji: '🇦🇬',
              phone: '1268',
              __typename: 'Country',
            },
            { name: 'Anguilla', code: 'AI', emoji: '🇦🇮', phone: '1264', __typename: 'Country' },
            { name: 'Albania', code: 'AL', emoji: '🇦🇱', phone: '355', __typename: 'Country' },
            { name: 'Armenia', code: 'AM', emoji: '🇦🇲', phone: '374', __typename: 'Country' },
            { name: 'Angola', code: 'AO', emoji: '🇦🇴', phone: '244', __typename: 'Country' },
            { name: 'Antarctica', code: 'AQ', emoji: '🇦🇶', phone: '672', __typename: 'Country' },
            { name: 'Argentina', code: 'AR', emoji: '🇦🇷', phone: '54', __typename: 'Country' },
            {
              name: 'American Samoa',
              code: 'AS',
              emoji: '🇦🇸',
              phone: '1684',
              __typename: 'Country',
            },
            { name: 'Austria', code: 'AT', emoji: '🇦🇹', phone: '43', __typename: 'Country' },
            { name: 'Australia', code: 'AU', emoji: '🇦🇺', phone: '61', __typename: 'Country' },
            { name: 'Aruba', code: 'AW', emoji: '🇦🇼', phone: '297', __typename: 'Country' },
            { name: 'Åland', code: 'AX', emoji: '🇦🇽', phone: '358', __typename: 'Country' },
            { name: 'Azerbaijan', code: 'AZ', emoji: '🇦🇿', phone: '994', __typename: 'Country' },
            {
              name: 'Bosnia and Herzegovina',
              code: 'BA',
              emoji: '🇧🇦',
              phone: '387',
              __typename: 'Country',
            },
            { name: 'Barbados', code: 'BB', emoji: '🇧🇧', phone: '1246', __typename: 'Country' },
            { name: 'Bangladesh', code: 'BD', emoji: '🇧🇩', phone: '880', __typename: 'Country' },
            { name: 'Belgium', code: 'BE', emoji: '🇧🇪', phone: '32', __typename: 'Country' },
            { name: 'Burkina Faso', code: 'BF', emoji: '🇧🇫', phone: '226', __typename: 'Country' },
            { name: 'Bulgaria', code: 'BG', emoji: '🇧🇬', phone: '359', __typename: 'Country' },
            { name: 'Bahrain', code: 'BH', emoji: '🇧🇭', phone: '973', __typename: 'Country' },
            { name: 'Burundi', code: 'BI', emoji: '🇧🇮', phone: '257', __typename: 'Country' },
            { name: 'Benin', code: 'BJ', emoji: '🇧🇯', phone: '229', __typename: 'Country' },
            {
              name: 'Saint Barthélemy',
              code: 'BL',
              emoji: '🇧🇱',
              phone: '590',
              __typename: 'Country',
            },
            { name: 'Bermuda', code: 'BM', emoji: '🇧🇲', phone: '1441', __typename: 'Country' },
            { name: 'Brunei', code: 'BN', emoji: '🇧🇳', phone: '673', __typename: 'Country' },
            { name: 'Bolivia', code: 'BO', emoji: '🇧🇴', phone: '591', __typename: 'Country' },
            { name: 'Bonaire', code: 'BQ', emoji: '🇧🇶', phone: '5997', __typename: 'Country' },
            { name: 'Brazil', code: 'BR', emoji: '🇧🇷', phone: '55', __typename: 'Country' },
            { name: 'Bahamas', code: 'BS', emoji: '🇧🇸', phone: '1242', __typename: 'Country' },
            { name: 'Bhutan', code: 'BT', emoji: '🇧🇹', phone: '975', __typename: 'Country' },
            { name: 'Bouvet Island', code: 'BV', emoji: '🇧🇻', phone: '47', __typename: 'Country' },
            { name: 'Botswana', code: 'BW', emoji: '🇧🇼', phone: '267', __typename: 'Country' },
            { name: 'Belarus', code: 'BY', emoji: '🇧🇾', phone: '375', __typename: 'Country' },
            { name: 'Belize', code: 'BZ', emoji: '🇧🇿', phone: '501', __typename: 'Country' },
            { name: 'Canada', code: 'CA', emoji: '🇨🇦', phone: '1', __typename: 'Country' },
            {
              name: 'Cocos [Keeling] Islands',
              code: 'CC',
              emoji: '🇨🇨',
              phone: '61',
              __typename: 'Country',
            },
            {
              name: 'Democratic Republic of the Congo',
              code: 'CD',
              emoji: '🇨🇩',
              phone: '243',
              __typename: 'Country',
            },
            {
              name: 'Central African Republic',
              code: 'CF',
              emoji: '🇨🇫',
              phone: '236',
              __typename: 'Country',
            },
            {
              name: 'Republic of the Congo',
              code: 'CG',
              emoji: '🇨🇬',
              phone: '242',
              __typename: 'Country',
            },
            { name: 'Switzerland', code: 'CH', emoji: '🇨🇭', phone: '41', __typename: 'Country' },
            { name: 'Ivory Coast', code: 'CI', emoji: '🇨🇮', phone: '225', __typename: 'Country' },
            { name: 'Cook Islands', code: 'CK', emoji: '🇨🇰', phone: '682', __typename: 'Country' },
            { name: 'Chile', code: 'CL', emoji: '🇨🇱', phone: '56', __typename: 'Country' },
            { name: 'Cameroon', code: 'CM', emoji: '🇨🇲', phone: '237', __typename: 'Country' },
            { name: 'China', code: 'CN', emoji: '🇨🇳', phone: '86', __typename: 'Country' },
            { name: 'Colombia', code: 'CO', emoji: '🇨🇴', phone: '57', __typename: 'Country' },
            { name: 'Costa Rica', code: 'CR', emoji: '🇨🇷', phone: '506', __typename: 'Country' },
            { name: 'Cuba', code: 'CU', emoji: '🇨🇺', phone: '53', __typename: 'Country' },
            { name: 'Cape Verde', code: 'CV', emoji: '🇨🇻', phone: '238', __typename: 'Country' },
            { name: 'Curacao', code: 'CW', emoji: '🇨🇼', phone: '5999', __typename: 'Country' },
            {
              name: 'Christmas Island',
              code: 'CX',
              emoji: '🇨🇽',
              phone: '61',
              __typename: 'Country',
            },
            { name: 'Cyprus', code: 'CY', emoji: '🇨🇾', phone: '357', __typename: 'Country' },
            {
              name: 'Czech Republic',
              code: 'CZ',
              emoji: '🇨🇿',
              phone: '420',
              __typename: 'Country',
            },
            { name: 'Germany', code: 'DE', emoji: '🇩🇪', phone: '49', __typename: 'Country' },
            { name: 'Djibouti', code: 'DJ', emoji: '🇩🇯', phone: '253', __typename: 'Country' },
            { name: 'Denmark', code: 'DK', emoji: '🇩🇰', phone: '45', __typename: 'Country' },
            { name: 'Dominica', code: 'DM', emoji: '🇩🇲', phone: '1767', __typename: 'Country' },
            {
              name: 'Dominican Republic',
              code: 'DO',
              emoji: '🇩🇴',
              phone: '1809,1829,1849',
              __typename: 'Country',
            },
            { name: 'Algeria', code: 'DZ', emoji: '🇩🇿', phone: '213', __typename: 'Country' },
            { name: 'Ecuador', code: 'EC', emoji: '🇪🇨', phone: '593', __typename: 'Country' },
            { name: 'Estonia', code: 'EE', emoji: '🇪🇪', phone: '372', __typename: 'Country' },
            { name: 'Egypt', code: 'EG', emoji: '🇪🇬', phone: '20', __typename: 'Country' },
            {
              name: 'Western Sahara',
              code: 'EH',
              emoji: '🇪🇭',
              phone: '212',
              __typename: 'Country',
            },
            { name: 'Eritrea', code: 'ER', emoji: '🇪🇷', phone: '291', __typename: 'Country' },
            { name: 'Spain', code: 'ES', emoji: '🇪🇸', phone: '34', __typename: 'Country' },
            { name: 'Ethiopia', code: 'ET', emoji: '🇪🇹', phone: '251', __typename: 'Country' },
            { name: 'Finland', code: 'FI', emoji: '🇫🇮', phone: '358', __typename: 'Country' },
            { name: 'Fiji', code: 'FJ', emoji: '🇫🇯', phone: '679', __typename: 'Country' },
            {
              name: 'Falkland Islands',
              code: 'FK',
              emoji: '🇫🇰',
              phone: '500',
              __typename: 'Country',
            },
            { name: 'Micronesia', code: 'FM', emoji: '🇫🇲', phone: '691', __typename: 'Country' },
            { name: 'Faroe Islands', code: 'FO', emoji: '🇫🇴', phone: '298', __typename: 'Country' },
            { name: 'France', code: 'FR', emoji: '🇫🇷', phone: '33', __typename: 'Country' },
            { name: 'Gabon', code: 'GA', emoji: '🇬🇦', phone: '241', __typename: 'Country' },
            { name: 'United Kingdom', code: 'GB', emoji: '🇬🇧', phone: '44', __typename: 'Country' },
            { name: 'Grenada', code: 'GD', emoji: '🇬🇩', phone: '1473', __typename: 'Country' },
            { name: 'Georgia', code: 'GE', emoji: '🇬🇪', phone: '995', __typename: 'Country' },
            { name: 'French Guiana', code: 'GF', emoji: '🇬🇫', phone: '594', __typename: 'Country' },
            { name: 'Guernsey', code: 'GG', emoji: '🇬🇬', phone: '44', __typename: 'Country' },
            { name: 'Ghana', code: 'GH', emoji: '🇬🇭', phone: '233', __typename: 'Country' },
            { name: 'Gibraltar', code: 'GI', emoji: '🇬🇮', phone: '350', __typename: 'Country' },
            { name: 'Greenland', code: 'GL', emoji: '🇬🇱', phone: '299', __typename: 'Country' },
            { name: 'Gambia', code: 'GM', emoji: '🇬🇲', phone: '220', __typename: 'Country' },
            { name: 'Guinea', code: 'GN', emoji: '🇬🇳', phone: '224', __typename: 'Country' },
            { name: 'Guadeloupe', code: 'GP', emoji: '🇬🇵', phone: '590', __typename: 'Country' },
            {
              name: 'Equatorial Guinea',
              code: 'GQ',
              emoji: '🇬🇶',
              phone: '240',
              __typename: 'Country',
            },
            { name: 'Greece', code: 'GR', emoji: '🇬🇷', phone: '30', __typename: 'Country' },
            {
              name: 'South Georgia and the South Sandwich Islands',
              code: 'GS',
              emoji: '🇬🇸',
              phone: '500',
              __typename: 'Country',
            },
            { name: 'Guatemala', code: 'GT', emoji: '🇬🇹', phone: '502', __typename: 'Country' },
            { name: 'Guam', code: 'GU', emoji: '🇬🇺', phone: '1671', __typename: 'Country' },
            { name: 'Guinea-Bissau', code: 'GW', emoji: '🇬🇼', phone: '245', __typename: 'Country' },
            { name: 'Guyana', code: 'GY', emoji: '🇬🇾', phone: '592', __typename: 'Country' },
            { name: 'Hong Kong', code: 'HK', emoji: '🇭🇰', phone: '852', __typename: 'Country' },
            {
              name: 'Heard Island and McDonald Islands',
              code: 'HM',
              emoji: '🇭🇲',
              phone: '61',
              __typename: 'Country',
            },
            { name: 'Honduras', code: 'HN', emoji: '🇭🇳', phone: '504', __typename: 'Country' },
            { name: 'Croatia', code: 'HR', emoji: '🇭🇷', phone: '385', __typename: 'Country' },
            { name: 'Haiti', code: 'HT', emoji: '🇭🇹', phone: '509', __typename: 'Country' },
            { name: 'Hungary', code: 'HU', emoji: '🇭🇺', phone: '36', __typename: 'Country' },
            { name: 'Indonesia', code: 'ID', emoji: '🇮🇩', phone: '62', __typename: 'Country' },
            { name: 'Ireland', code: 'IE', emoji: '🇮🇪', phone: '353', __typename: 'Country' },
            { name: 'Israel', code: 'IL', emoji: '🇮🇱', phone: '972', __typename: 'Country' },
            { name: 'Isle of Man', code: 'IM', emoji: '🇮🇲', phone: '44', __typename: 'Country' },
            { name: 'India', code: 'IN', emoji: '🇮🇳', phone: '91', __typename: 'Country' },
            {
              name: 'British Indian Ocean Territory',
              code: 'IO',
              emoji: '🇮🇴',
              phone: '246',
              __typename: 'Country',
            },
            { name: 'Iraq', code: 'IQ', emoji: '🇮🇶', phone: '964', __typename: 'Country' },
            { name: 'Iran', code: 'IR', emoji: '🇮🇷', phone: '98', __typename: 'Country' },
            { name: 'Iceland', code: 'IS', emoji: '🇮🇸', phone: '354', __typename: 'Country' },
            { name: 'Italy', code: 'IT', emoji: '🇮🇹', phone: '39', __typename: 'Country' },
            { name: 'Jersey', code: 'JE', emoji: '🇯🇪', phone: '44', __typename: 'Country' },
            { name: 'Jamaica', code: 'JM', emoji: '🇯🇲', phone: '1876', __typename: 'Country' },
            { name: 'Jordan', code: 'JO', emoji: '🇯🇴', phone: '962', __typename: 'Country' },
            { name: 'Japan', code: 'JP', emoji: '🇯🇵', phone: '81', __typename: 'Country' },
            { name: 'Kenya', code: 'KE', emoji: '🇰🇪', phone: '254', __typename: 'Country' },
            { name: 'Kyrgyzstan', code: 'KG', emoji: '🇰🇬', phone: '996', __typename: 'Country' },
            { name: 'Cambodia', code: 'KH', emoji: '🇰🇭', phone: '855', __typename: 'Country' },
            { name: 'Kiribati', code: 'KI', emoji: '🇰🇮', phone: '686', __typename: 'Country' },
            { name: 'Comoros', code: 'KM', emoji: '🇰🇲', phone: '269', __typename: 'Country' },
            {
              name: 'Saint Kitts and Nevis',
              code: 'KN',
              emoji: '🇰🇳',
              phone: '1869',
              __typename: 'Country',
            },
            { name: 'North Korea', code: 'KP', emoji: '🇰🇵', phone: '850', __typename: 'Country' },
            { name: 'South Korea', code: 'KR', emoji: '🇰🇷', phone: '82', __typename: 'Country' },
            { name: 'Kuwait', code: 'KW', emoji: '🇰🇼', phone: '965', __typename: 'Country' },
            {
              name: 'Cayman Islands',
              code: 'KY',
              emoji: '🇰🇾',
              phone: '1345',
              __typename: 'Country',
            },
            { name: 'Kazakhstan', code: 'KZ', emoji: '🇰🇿', phone: '76,77', __typename: 'Country' },
            { name: 'Laos', code: 'LA', emoji: '🇱🇦', phone: '856', __typename: 'Country' },
            { name: 'Lebanon', code: 'LB', emoji: '🇱🇧', phone: '961', __typename: 'Country' },
            { name: 'Saint Lucia', code: 'LC', emoji: '🇱🇨', phone: '1758', __typename: 'Country' },
            { name: 'Liechtenstein', code: 'LI', emoji: '🇱🇮', phone: '423', __typename: 'Country' },
            { name: 'Sri Lanka', code: 'LK', emoji: '🇱🇰', phone: '94', __typename: 'Country' },
            { name: 'Liberia', code: 'LR', emoji: '🇱🇷', phone: '231', __typename: 'Country' },
            { name: 'Lesotho', code: 'LS', emoji: '🇱🇸', phone: '266', __typename: 'Country' },
            { name: 'Lithuania', code: 'LT', emoji: '🇱🇹', phone: '370', __typename: 'Country' },
            { name: 'Luxembourg', code: 'LU', emoji: '🇱🇺', phone: '352', __typename: 'Country' },
            { name: 'Latvia', code: 'LV', emoji: '🇱🇻', phone: '371', __typename: 'Country' },
            { name: 'Libya', code: 'LY', emoji: '🇱🇾', phone: '218', __typename: 'Country' },
            { name: 'Morocco', code: 'MA', emoji: '🇲🇦', phone: '212', __typename: 'Country' },
            { name: 'Monaco', code: 'MC', emoji: '🇲🇨', phone: '377', __typename: 'Country' },
            { name: 'Moldova', code: 'MD', emoji: '🇲🇩', phone: '373', __typename: 'Country' },
            { name: 'Montenegro', code: 'ME', emoji: '🇲🇪', phone: '382', __typename: 'Country' },
            { name: 'Saint Martin', code: 'MF', emoji: '🇲🇫', phone: '590', __typename: 'Country' },
            { name: 'Madagascar', code: 'MG', emoji: '🇲🇬', phone: '261', __typename: 'Country' },
            {
              name: 'Marshall Islands',
              code: 'MH',
              emoji: '🇲🇭',
              phone: '692',
              __typename: 'Country',
            },
            {
              name: 'North Macedonia',
              code: 'MK',
              emoji: '🇲🇰',
              phone: '389',
              __typename: 'Country',
            },
            { name: 'Mali', code: 'ML', emoji: '🇲🇱', phone: '223', __typename: 'Country' },
            {
              name: 'Myanmar [Burma]',
              code: 'MM',
              emoji: '🇲🇲',
              phone: '95',
              __typename: 'Country',
            },
            { name: 'Mongolia', code: 'MN', emoji: '🇲🇳', phone: '976', __typename: 'Country' },
            { name: 'Macao', code: 'MO', emoji: '🇲🇴', phone: '853', __typename: 'Country' },
            {
              name: 'Northern Mariana Islands',
              code: 'MP',
              emoji: '🇲🇵',
              phone: '1670',
              __typename: 'Country',
            },
            { name: 'Martinique', code: 'MQ', emoji: '🇲🇶', phone: '596', __typename: 'Country' },
            { name: 'Mauritania', code: 'MR', emoji: '🇲🇷', phone: '222', __typename: 'Country' },
            { name: 'Montserrat', code: 'MS', emoji: '🇲🇸', phone: '1664', __typename: 'Country' },
            { name: 'Malta', code: 'MT', emoji: '🇲🇹', phone: '356', __typename: 'Country' },
            { name: 'Mauritius', code: 'MU', emoji: '🇲🇺', phone: '230', __typename: 'Country' },
            { name: 'Maldives', code: 'MV', emoji: '🇲🇻', phone: '960', __typename: 'Country' },
            { name: 'Malawi', code: 'MW', emoji: '🇲🇼', phone: '265', __typename: 'Country' },
            { name: 'Mexico', code: 'MX', emoji: '🇲🇽', phone: '52', __typename: 'Country' },
            { name: 'Malaysia', code: 'MY', emoji: '🇲🇾', phone: '60', __typename: 'Country' },
            { name: 'Mozambique', code: 'MZ', emoji: '🇲🇿', phone: '258', __typename: 'Country' },
            { name: 'Namibia', code: 'NA', emoji: '🇳🇦', phone: '264', __typename: 'Country' },
            { name: 'New Caledonia', code: 'NC', emoji: '🇳🇨', phone: '687', __typename: 'Country' },
            { name: 'Niger', code: 'NE', emoji: '🇳🇪', phone: '227', __typename: 'Country' },
            {
              name: 'Norfolk Island',
              code: 'NF',
              emoji: '🇳🇫',
              phone: '672',
              __typename: 'Country',
            },
            { name: 'Nigeria', code: 'NG', emoji: '🇳🇬', phone: '234', __typename: 'Country' },
            { name: 'Nicaragua', code: 'NI', emoji: '🇳🇮', phone: '505', __typename: 'Country' },
            { name: 'Netherlands', code: 'NL', emoji: '🇳🇱', phone: '31', __typename: 'Country' },
            { name: 'Norway', code: 'NO', emoji: '🇳🇴', phone: '47', __typename: 'Country' },
            { name: 'Nepal', code: 'NP', emoji: '🇳🇵', phone: '977', __typename: 'Country' },
            { name: 'Nauru', code: 'NR', emoji: '🇳🇷', phone: '674', __typename: 'Country' },
            { name: 'Niue', code: 'NU', emoji: '🇳🇺', phone: '683', __typename: 'Country' },
            { name: 'New Zealand', code: 'NZ', emoji: '🇳🇿', phone: '64', __typename: 'Country' },
            { name: 'Oman', code: 'OM', emoji: '🇴🇲', phone: '968', __typename: 'Country' },
            { name: 'Panama', code: 'PA', emoji: '🇵🇦', phone: '507', __typename: 'Country' },
            { name: 'Peru', code: 'PE', emoji: '🇵🇪', phone: '51', __typename: 'Country' },
            {
              name: 'French Polynesia',
              code: 'PF',
              emoji: '🇵🇫',
              phone: '689',
              __typename: 'Country',
            },
            {
              name: 'Papua New Guinea',
              code: 'PG',
              emoji: '🇵🇬',
              phone: '675',
              __typename: 'Country',
            },
            { name: 'Philippines', code: 'PH', emoji: '🇵🇭', phone: '63', __typename: 'Country' },
            { name: 'Pakistan', code: 'PK', emoji: '🇵🇰', phone: '92', __typename: 'Country' },
            { name: 'Poland', code: 'PL', emoji: '🇵🇱', phone: '48', __typename: 'Country' },
            {
              name: 'Saint Pierre and Miquelon',
              code: 'PM',
              emoji: '🇵🇲',
              phone: '508',
              __typename: 'Country',
            },
            {
              name: 'Pitcairn Islands',
              code: 'PN',
              emoji: '🇵🇳',
              phone: '64',
              __typename: 'Country',
            },
            {
              name: 'Puerto Rico',
              code: 'PR',
              emoji: '🇵🇷',
              phone: '1787,1939',
              __typename: 'Country',
            },
            { name: 'Palestine', code: 'PS', emoji: '🇵🇸', phone: '970', __typename: 'Country' },
            { name: 'Portugal', code: 'PT', emoji: '🇵🇹', phone: '351', __typename: 'Country' },
            { name: 'Palau', code: 'PW', emoji: '🇵🇼', phone: '680', __typename: 'Country' },
            { name: 'Paraguay', code: 'PY', emoji: '🇵🇾', phone: '595', __typename: 'Country' },
            { name: 'Qatar', code: 'QA', emoji: '🇶🇦', phone: '974', __typename: 'Country' },
            { name: 'Réunion', code: 'RE', emoji: '🇷🇪', phone: '262', __typename: 'Country' },
            { name: 'Romania', code: 'RO', emoji: '🇷🇴', phone: '40', __typename: 'Country' },
            { name: 'Serbia', code: 'RS', emoji: '🇷🇸', phone: '381', __typename: 'Country' },
            { name: 'Russia', code: 'RU', emoji: '🇷🇺', phone: '7', __typename: 'Country' },
            { name: 'Rwanda', code: 'RW', emoji: '🇷🇼', phone: '250', __typename: 'Country' },
            { name: 'Saudi Arabia', code: 'SA', emoji: '🇸🇦', phone: '966', __typename: 'Country' },
            {
              name: 'Solomon Islands',
              code: 'SB',
              emoji: '🇸🇧',
              phone: '677',
              __typename: 'Country',
            },
            { name: 'Seychelles', code: 'SC', emoji: '🇸🇨', phone: '248', __typename: 'Country' },
            { name: 'Sudan', code: 'SD', emoji: '🇸🇩', phone: '249', __typename: 'Country' },
            { name: 'Sweden', code: 'SE', emoji: '🇸🇪', phone: '46', __typename: 'Country' },
            { name: 'Singapore', code: 'SG', emoji: '🇸🇬', phone: '65', __typename: 'Country' },
            { name: 'Saint Helena', code: 'SH', emoji: '🇸🇭', phone: '290', __typename: 'Country' },
            { name: 'Slovenia', code: 'SI', emoji: '🇸🇮', phone: '386', __typename: 'Country' },
            {
              name: 'Svalbard and Jan Mayen',
              code: 'SJ',
              emoji: '🇸🇯',
              phone: '4779',
              __typename: 'Country',
            },
            { name: 'Slovakia', code: 'SK', emoji: '🇸🇰', phone: '421', __typename: 'Country' },
            { name: 'Sierra Leone', code: 'SL', emoji: '🇸🇱', phone: '232', __typename: 'Country' },
            { name: 'San Marino', code: 'SM', emoji: '🇸🇲', phone: '378', __typename: 'Country' },
            { name: 'Senegal', code: 'SN', emoji: '🇸🇳', phone: '221', __typename: 'Country' },
            { name: 'Somalia', code: 'SO', emoji: '🇸🇴', phone: '252', __typename: 'Country' },
            { name: 'Suriname', code: 'SR', emoji: '🇸🇷', phone: '597', __typename: 'Country' },
            { name: 'South Sudan', code: 'SS', emoji: '🇸🇸', phone: '211', __typename: 'Country' },
            {
              name: 'São Tomé and Príncipe',
              code: 'ST',
              emoji: '🇸🇹',
              phone: '239',
              __typename: 'Country',
            },
            { name: 'El Salvador', code: 'SV', emoji: '🇸🇻', phone: '503', __typename: 'Country' },
            { name: 'Sint Maarten', code: 'SX', emoji: '🇸🇽', phone: '1721', __typename: 'Country' },
            { name: 'Syria', code: 'SY', emoji: '🇸🇾', phone: '963', __typename: 'Country' },
            { name: 'Swaziland', code: 'SZ', emoji: '🇸🇿', phone: '268', __typename: 'Country' },
            {
              name: 'Turks and Caicos Islands',
              code: 'TC',
              emoji: '🇹🇨',
              phone: '1649',
              __typename: 'Country',
            },
            { name: 'Chad', code: 'TD', emoji: '🇹🇩', phone: '235', __typename: 'Country' },
            {
              name: 'French Southern Territories',
              code: 'TF',
              emoji: '🇹🇫',
              phone: '262',
              __typename: 'Country',
            },
            { name: 'Togo', code: 'TG', emoji: '🇹🇬', phone: '228', __typename: 'Country' },
            { name: 'Thailand', code: 'TH', emoji: '🇹🇭', phone: '66', __typename: 'Country' },
            { name: 'Tajikistan', code: 'TJ', emoji: '🇹🇯', phone: '992', __typename: 'Country' },
            { name: 'Tokelau', code: 'TK', emoji: '🇹🇰', phone: '690', __typename: 'Country' },
            { name: 'East Timor', code: 'TL', emoji: '🇹🇱', phone: '670', __typename: 'Country' },
            { name: 'Turkmenistan', code: 'TM', emoji: '🇹🇲', phone: '993', __typename: 'Country' },
            { name: 'Tunisia', code: 'TN', emoji: '🇹🇳', phone: '216', __typename: 'Country' },
            { name: 'Tonga', code: 'TO', emoji: '🇹🇴', phone: '676', __typename: 'Country' },
            { name: 'Turkey', code: 'TR', emoji: '🇹🇷', phone: '90', __typename: 'Country' },
            {
              name: 'Trinidad and Tobago',
              code: 'TT',
              emoji: '🇹🇹',
              phone: '1868',
              __typename: 'Country',
            },
            { name: 'Tuvalu', code: 'TV', emoji: '🇹🇻', phone: '688', __typename: 'Country' },
            { name: 'Taiwan', code: 'TW', emoji: '🇹🇼', phone: '886', __typename: 'Country' },
            { name: 'Tanzania', code: 'TZ', emoji: '🇹🇿', phone: '255', __typename: 'Country' },
            { name: 'Ukraine', code: 'UA', emoji: '🇺🇦', phone: '380', __typename: 'Country' },
            { name: 'Uganda', code: 'UG', emoji: '🇺🇬', phone: '256', __typename: 'Country' },
            {
              name: 'U.S. Minor Outlying Islands',
              code: 'UM',
              emoji: '🇺🇲',
              phone: '1',
              __typename: 'Country',
            },
            { name: 'United States', code: 'US', emoji: '🇺🇸', phone: '1', __typename: 'Country' },
            { name: 'Uruguay', code: 'UY', emoji: '🇺🇾', phone: '598', __typename: 'Country' },
            { name: 'Uzbekistan', code: 'UZ', emoji: '🇺🇿', phone: '998', __typename: 'Country' },
            { name: 'Vatican City', code: 'VA', emoji: '🇻🇦', phone: '379', __typename: 'Country' },
            {
              name: 'Saint Vincent and the Grenadines',
              code: 'VC',
              emoji: '🇻🇨',
              phone: '1784',
              __typename: 'Country',
            },
            { name: 'Venezuela', code: 'VE', emoji: '🇻🇪', phone: '58', __typename: 'Country' },
            {
              name: 'British Virgin Islands',
              code: 'VG',
              emoji: '🇻🇬',
              phone: '1284',
              __typename: 'Country',
            },
            {
              name: 'U.S. Virgin Islands',
              code: 'VI',
              emoji: '🇻🇮',
              phone: '1340',
              __typename: 'Country',
            },
            { name: 'Vietnam', code: 'VN', emoji: '🇻🇳', phone: '84', __typename: 'Country' },
            { name: 'Vanuatu', code: 'VU', emoji: '🇻🇺', phone: '678', __typename: 'Country' },
            {
              name: 'Wallis and Futuna',
              code: 'WF',
              emoji: '🇼🇫',
              phone: '681',
              __typename: 'Country',
            },
            { name: 'Samoa', code: 'WS', emoji: '🇼🇸', phone: '685', __typename: 'Country' },
            {
              name: 'Kosovo',
              code: 'XK',
              emoji: '🇽🇰',
              phone: '377,381,383,386',
              __typename: 'Country',
            },
            { name: 'Yemen', code: 'YE', emoji: '🇾🇪', phone: '967', __typename: 'Country' },
            { name: 'Mayotte', code: 'YT', emoji: '🇾🇹', phone: '262', __typename: 'Country' },
            { name: 'South Africa', code: 'ZA', emoji: '🇿🇦', phone: '27', __typename: 'Country' },
            { name: 'Zambia', code: 'ZM', emoji: '🇿🇲', phone: '260', __typename: 'Country' },
            { name: 'Zimbabwe', code: 'ZW', emoji: '🇿🇼', phone: '263', __typename: 'Country' },
          ],
        },
      },
    },
  ];
  renderApollo(<CountryList path="/" />, { cache, mocks });

  const pageTitle = screen.getByText(/countries/i);
  expect(pageTitle).toBeInTheDocument();
});
